apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  
---

apiVersion: v1
kind: Deployment
metadata: 
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb
        name: influxdb
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim
      restartPolicy: Always
      volumes:
      - name: influxdb-claim
        persistentVolumeClaim:
          claimName: influxdb-claim
