version: '3'
services:
  influxdb:
    image: "influxdb"
    ports:
    - 8086:8086
    volumes:
    - ~/dockerDirs/influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - ~/dockerDirs/grafana-data:/var/lib/grafana