version: '3'
services:
  influxdb:
    image: "influxdb"
    ports:
    - 8086:8086
    volumes:
    - ~/dockerDirs/influxdb-data:/var/lib/influxdb

  api:
    image: pskreter/db-api:stable
    restart: always
    ports:
    - 8080:8080