version: '3'
services:
  influxdb:
    image: "influxdb"
    ports:
    - 8086:8086
    volumes:
    - /devdisk/influxdb-data:/var/lib/influxdb

  api:
    image: pskreter/db-api:stable
    ports:
    - 80:8080